<template>
  <div>
    <div class="sidebar"><sidebar /></div>
    <div class="dropdown">
      <v-container>
        <v-layout row wrap>
          <v-flex xs12>
            <v-select
              v-model="e1"
              :menu-props="{ auto: true }"
              :items="internship"
              label="Time for compulsory internship"
              placeholder="Year 3 Sem 1"
              attach="dropdown"
            ></v-select>
            <v-select
              v-model="e2"
              :menu-props="{ auto: true }"
              :items="sep"
              label="Time for SEP"
              placeholder="Year 3 Sem 2"
              attach="dropdown"
            ></v-select>
            <v-select
              v-model="e3"
              :menu-props="{ auto: true }"
              :items="minors"
              label="Minor to take"
              placeholder="No Plan"
              attach="dropdown"
            ></v-select>
            <v-select
              v-model="e4"
              :menu-props="{ auto: true }"
              :items="specs"
              label="Specialisation to take"
              placeholder="Financial Analytics"
              attach="dropdown"
            ></v-select>
            <v-select
              v-model="e5"
              :menu-props="{ auto: true }"
              :items="skills"
              label="Technical Skills Focus"
              placeholder="No Plan"
              attach="dropdown"
            ></v-select>
            <v-btn block color="teal lighten-2" dark @click="isSubmitted()">Submit</v-btn>
            <v-btn block color="teal lighten-2" dark @click="isReset()">Reset</v-btn>
            <v-spacer></v-spacer>
          
            <v-btn block color="teal lighten-2" dark :title="runCreateMSG" @click="toCreate()">Create</v-btn>
          </v-flex>
        </v-layout>
      </v-container>
    </div>
    <div class="studyplan_blank" v-show="submitted==0">
    <img src="https://firebasestorage.googleapis.com/v0/b/nusplanner.appspot.com/o/studyplans%2Fstudyplan_blank.PNG?alt=media&token=f3c61f92-d6bf-41ec-b6e3-86c142ecc69d" width="750px" height="500px" />
    </div>
    <div class="studyplan" v-show="submitted==1">
    <img src='https://firebasestorage.googleapis.com/v0/b/nusplanner.appspot.com/o/studyplans%2Fstudyplan_ec.PNG?alt=media&token=2d2dac88-463a-4af8-8b8f-33b806f50bbb' width="750px" height="500px" />
    </div>
    <div class="studyplan" v-show="submitted==2">
    <img src='https://firebasestorage.googleapis.com/v0/b/nusplanner.appspot.com/o/studyplans%2Fstudyplan_ec_in4.PNG?alt=media&token=192d9567-33cf-449d-b71d-775ef354c278' width="750px" height="500px" />
    </div>
    <div class="studyplan" v-show="submitted==3">
    <img src='https://firebasestorage.googleapis.com/v0/b/nusplanner.appspot.com/o/studyplans%2Fstudyplan_ec_nosep.PNG?alt=media&token=7acd4352-df56-4642-a88d-e20b9ac527fe' width="750px" height="500px" />
    </div>
    <div class="studyplan" v-show="submitted==4">
    <img src='https://firebasestorage.googleapis.com/v0/b/nusplanner.appspot.com/o/studyplans%2Fstudyplan_sep5_st.PNG?alt=media&token=073b0f3a-5d7a-4fc1-ab33-7e3a4a76da71' width="750px" height="500px" />
    </div>
    <div class='para'>
      <p>
      ***For lists of program elective, please click <a href="https://www.comp.nus.edu.sg/cugresource/per-cohort/ba/ba-18-19/">BZA official webpages.</a> <br>
      ***All study plans are generated by past BZA students four year module plans and will update every semester.<br>
      ***All modules marked in red are subject to user preference.<br>
      ***Visit our recommendation tab for more inspiration!
    </p>
    </div>
    
    
  </div>
</template>

<script>
import sidebar from "@/components/Sidebar.vue";
import router from '@/router/index.js';

export default {
  name: "four_year_plan",
  components: {
    sidebar
  },
  data() {
    return {
      runCreateMSG: "Create and view your own plan",
      submitted: 1,
      e1: [],
      e2: [],
      e3: [],
      e4: [],
      e5: [],
      internship: [
        "Year 2 Sem 2",
        "Year 3 Sem 1",
        "Year 3 Sem 2"
      ],
      sep: [
        "Year 2 Sem 2",
        "Year 3 Sem 1",
        "Year 3 Sem 2",
        "No Plan"
      ],
      minors: [
        "Economics",
        "Statistics",
        "No Plan"
      ],
      specs: [
        "Financial Analytics",
        "Marketing Analytics",
        "No Plan"
      ],
      skills: [
        "Python Programming",
        "No Plan"
      ]
    };
  },
  methods: {
    isSubmitted: function()
    {
      if(this.e1=="Year 3 Sem 1" && this.e2 == "Year 3 Sem 2" && this.e3 =="Economics" ){
        this.submitted = 1;
      } else if(this.e1=="Year 2 Sem 2" && this.e2 == "Year 3 Sem 2" && this.e3 =="Economics" ){
        this.submitted = 2;
      }else if(this.e1=="Year 2 Sem 2" && this.e2 == "No Plan" && this.e3 =="Economics" ){
        this.submitted =3;
      }else if(this.e1=="Year 3 Sem 2" && this.e2 == "Year 2 Sem 2" && this.e3 =="Statistics" ){
        this.submitted =4;
      }
      else{
        alert("We are sorry, there is no study plan for this combination. Please reselect or create your own plan. We will update soon");
        this.submitted = 0;
      }
    },
    isReset: function()
    {
      this.submitted = 0;
    },
    toCreate: function()
    {
      router.push({name: 'create_plan'})
    }
  }
};
</script>

<style scoped>
#four_year_plan {
  background-color: #ffffff;
  margin: auto;
  width: 100%;
}
.sidebar {
  background-color: #ffffff;
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  width: 20%;
  float: left;
}
.dropdown {
  width: 20%;
  float: left;
}
.studyplan .studyplan_blank {
  width: 50%;
  float: left;

}
.para{
  width:60%;
  float:right;
}
h1,
h2 {
  font-weight: normal;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>
